import locale

if locale.getdefaultlocale()[0] == "es_ES":
    import utils.constants.spanish as constants
else:
    import utils.constants.english as constants

APP_NAME = "My Bookshelf"
# No GUI Constants
WELCOME_MESSAGE = constants.WELCOME_MESSAGE
OPTION = constants.OPTION
UNKNOWN_OPTION = constants.UNKNOWN_OPTION
ADVANCED_SEARCH_INPUT = constants.ADVANCED_SEARCH_INPUT
ADVANCED_SEARCH_SPECIFIC_INPUT = constants.ADVANCED_SEARCH_SPECIFIC_INPUT
ADD_SEARCH_TERM = constants.ADD_SEARCH_TERM
SELECT_FIELD = constants.SELECT_FIELD
LOOKING_FOR = constants.LOOKING_FOR
WISH_TO_SEE_MORE = constants.WISH_TO_SEE_MORE
SELECT_ONE_BOOK_TO_SEE_DETAILS = constants.SELECT_ONE_BOOK_TO_SEE_DETAILS
FOUND = constants.FOUND
WISH_TO_ADD_TO_YOUR_BOOKS = constants.WISH_TO_ADD_TO_YOUR_BOOKS
DISPLAY_BOOK_NO_GUI_ARRAY = constants.DISPLAY_BOOK_NO_GUI_ARRAY
EXIT = constants.EXIT
NO_BOOKS = constants.NO_BOOKS
MY_BOOKS_ARRAY = constants.MY_BOOKS_ARRAY
DISPLAY_USER_BOOK_ARRAY = constants.DISPLAY_USER_BOOK_ARRAY
WISH_TO_CHANGE_STATUS = constants.WISH_TO_CHANGE_STATUS
READING_OR_WANT_TO_READ = constants.READING_OR_WANT_TO_READ
READ_OR_WANT_TO_READ = constants.READ_OR_WANT_TO_READ
READ_OR_READING = constants.READ_OR_READING
EXPORT_TO_EXCEL_INPUT = constants.EXPORT_TO_EXCEL_INPUT
# GUI Constants
MAIN_OPTIONS = constants.MAIN_OPTIONS
USER_BOOK_TABS = constants.USER_BOOK_TABS
SEARCH_TYPES = constants.SEARCH_TYPES
ORDER_BY = constants.ORDER_BY
ORDER_BY_ARRAY = constants.ORDER_BY_ARRAY
EXCEL_HEADERS = constants.EXCEL_HEADERS
UNKNOWN = constants.UNKNOWN
FROM = constants.FROM
PUBLISHED_BY = constants.PUBLISHED_BY
UNKNOWN_PUBLISHER = constants.UNKNOWN_PUBLISHER
PUBLISHED_DATE = constants.PUBLISHED_DATE
UNKNOWN_PUBLISHED_DATE = constants.UNKNOWN_PUBLISHED_DATE
PAGES = constants.PAGES
UNKNOWN_PAGES = constants.UNKNOWN_PAGES
UNKNOWN_DESCRIPTION = constants.UNKNOWN_DESCRIPTION
REVIEWS_BY_REGEX = constants.REVIEWS_BY_REGEX
BY = constants.BY
CATEGORIES = constants.CATEGORIES
LANGUAGE = constants.LANGUAGE
UNKNOWN_LANGUAGE = constants.UNKNOWN_LANGUAGE
HAS_READ = constants.HAS_READ
ARE_READING = constants.ARE_READING
WANT_TO_READ = constants.WANT_TO_READ
BOOKS = constants.BOOKS
BOOK = constants.BOOK
IN_TOTAL = constants.IN_TOTAL
EXPORT_TO_EXCEL = constants.EXPORT_TO_EXCEL
SAVE_ARCHIVE = constants.SAVE_ARCHIVE
SUCCESS_EXPORT = constants.SUCCESS_EXPORT
REMOVE_FROM_MY_BOOKS = constants.REMOVE_FROM_MY_BOOKS
LAST_UPDATE = constants.LAST_UPDATE
DATE_FORMAT = constants.DATE_FORMAT
SIMPLE_SEARCH = constants.SIMPLE_SEARCH
ADVANCED_SEARCH = constants.ADVANCED_SEARCH
